### ISSUE TITLE
Failing to run on other machines

### ISSUE THREAD

**Issue by AlDrag** [hbomb79/Thea#27]
Receiving this error when running `go run .`.

```
internal/ffmpeg/commander.go:7:2: github.com/floostack/transcoder@v1.1.2-0.20210806093423-9367de148a50: replacement directory /home/haz/go/src/transcoder does not exist
internal/core_service.go:4:2: github.com/floostack/transcoder@v1.1.2-0.20210806093423-9367de148a50: replacement directory /home/haz/go/src/transcoder does not exist
```

I assume you have some hardcoded paths still referencing your machine (i.ie `haz`). But could be wrong...

**Comment by hbomb79** [comment]
Ah damn, thanks for catching that Alan :)

I've been developing against a local temporary fork of `floostack/transcoder` for so long now that I totally forgot about it. I've fixed it in `develop` now, so feel free to checkout and pull from that branch. Hopefully everything will work as expected now.
